### ISSUE TITLE
HTML encoding special chars

### ISSUE THREAD

**Issue by moowsje** [qoda/python-mailer#4]
When sending a HTML formatted email with the  variable and inserting a name containing international characters the characters are not displayed correctly (like: ó becomes Ã³ and ö becomes Ã¶).

This can be fixed by altering the source code and modify the mail header sent with python-mailer.
Change line 128 from: email_message.add_header('Content-Type', 'text/html')
To:  email_message.add_header('Content-Type', 'text/html; charset="utf-8"')

Can you please fix this?

**Comment by qoda** [comment]
Better late that never... Fixed in master
